In [1]:
import numpy as np


In [2]:
a = np.random.rand(3,2)

In [3]:
print(a)

[[0.82780036 0.02913045]
 [0.17887251 0.78113168]
 [0.8626026  0.41531216]]


In [4]:
a = np.random.rand(10)

In [7]:
b =a*10

In [8]:
a

array([0.28821594, 0.38267424, 0.49549104, 0.67191986, 0.55845889,
       0.67354239, 0.25825639, 0.78016453, 0.85294825, 0.26105998])

In [9]:
b

array([2.88215944, 3.82674243, 4.95491039, 6.71919857, 5.58458888,
       6.73542392, 2.58256394, 7.80164533, 8.5294825 , 2.61059984])

In [10]:
b/10

array([0.28821594, 0.38267424, 0.49549104, 0.67191986, 0.55845889,
       0.67354239, 0.25825639, 0.78016453, 0.85294825, 0.26105998])

In [11]:
a

array([0.28821594, 0.38267424, 0.49549104, 0.67191986, 0.55845889,
       0.67354239, 0.25825639, 0.78016453, 0.85294825, 0.26105998])

In [18]:
c = np.random.rand(1000000)

In [19]:
c

array([0.11693085, 0.60862941, 0.82377116, ..., 0.6105793 , 0.4463438 ,
       0.67773118])

In [20]:
print(c)

[0.11693085 0.60862941 0.82377116 ... 0.6105793  0.4463438  0.67773118]


In [21]:
c[1]

0.608629409246648

In [28]:
c.min

<function ndarray.min>

In [30]:
print(c.max())

0.9999998083672049


In [40]:
np.random.randn(4)

array([-0.3544839 ,  0.85175873, -0.65722648, -1.16072364])